[experiment]
name = "hyp2_sphere_lhs2"
output_dir = "results/thesis_lhs/hyp2/sphere/hyp2_sphere_lhs2"

[experiment.shared]
fitness = "bbob:fn_name=sphere,num_dims=75,maximize=false"
selection = "elite_pool:num_selections=411,elite_k=68"
pop_size = 411
generations = 958
genome_length = 75
bounds = [ -5.0, 5.0,]
seeds = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100,]
backend = "malthusjax"
elitism = 0
crossover = "uniform_crossover:crossover_rate=0.3"
serialize_history = false

[pipelines.mjx_native_mutation]
mutation = "gaussian:sigma=0.05"

[pipelines.mjx_evosax_mutation_wrapper]
mutation = "evosax_gaussian:mutation_strength=0.05"
