[experiment]
name = "hyp1_rosenbrock_lhs0"
output_dir = "results/thesis_lhs/hyp1/rosenbrock/hyp1_rosenbrock_lhs0"

[experiment.shared]
fitness = "bbob:fn_name=rosenbrock,num_dims=24,maximize=false"
selection = "evosax_mimic_selection:num_selections=566,elite_k=94"
pop_size = 566
generations = 150
genome_length = 24
bounds = [ -5.0, 5.0,]
seeds = [ 1, 2,]
serialize_history = false

[pipelines.malthusjax_wrapper]
backend = "malthusjax"
elitism = 0
crossover = "evosax_uniform_crossover:crossover_rate=0.3"
mutation = "evosax_gaussian:mutation_strength=0.05"

[pipelines.evosax_baseline]
backend = "evosax"
evosax_strategy = "SimpleGA"

[pipelines.evosax_baseline.strategy_params]
crossover_rate = 0.3
elite_ratio = 0.16666666666666666
