[experiment]
name = "hyp2_rastrigin_lhs0"
output_dir = "results/thesis_lhs/hyp2/rastrigin/hyp2_rastrigin_lhs0"

[experiment.shared]
fitness = "bbob:fn_name=rastrigin,num_dims=24,maximize=false"
pop_size = 566
generations = 150
genome_length = 24
bounds = [ -5.0, 5.0,]
seeds = [ 1, 2,]
backend = "malthusjax"
elitism = 0
serialize_history = false

[pipelines.mjx_native_mutation]
selection = "evosax_mimic_selection:num_selections=566,elite_k=94"
crossover = "evosax_uniform_crossover:crossover_rate=0.3"
mutation = "gaussian:mutation_strength=0.05"

[pipelines.mjx_native_crossover]
selection = "evosax_mimic_selection:num_selections=566,elite_k=94"
crossover = "uniform_real:crossover_rate=0.3"
mutation = "evosax_gaussian:mutation_strength=0.05"

[pipelines.mjx_native_selection_elite]
selection = "elite_pool:num_selections=566,elite_k=94"
crossover = "evosax_uniform_crossover:crossover_rate=0.3"
mutation = "evosax_gaussian:mutation_strength=0.05"

[pipelines.mjx_native_selection_tournament]
selection = "tournament:num_selections=566,tournament_size=3"
crossover = "evosax_uniform_crossover:crossover_rate=0.3"
mutation = "evosax_gaussian:mutation_strength=0.05"
