"""Evosax strategy adapter for the BenchmarkRunner.Engine protocol.

Wraps any evosax population-based strategy using the universal @adapter decorator.
"""

from __future__ import annotations

from typing import Any, Callable, Dict, Optional, Sequence, Tuple

import chex
import jax
import jax.numpy as jnp
from evosax.algorithms import distribution_based_algorithms, population_based_algorithms

from malthusjax.composer.adapters import EvalMode, adapter

EVOSAX_STRATEGIES: Dict[str, type] = {
    **population_based_algorithms,
    **distribution_based_algorithms,
}


def list_strategies() -> list[str]:
    """Return available evosax strategy names."""
    return sorted(EVOSAX_STRATEGIES.keys())


def _evosax_native_eval(evaluator, pop, state, key):
    """Executes the evosax native problem evaluation."""
    if hasattr(evaluator, "evosax_problem"):
        problem = evaluator.evosax_problem
        p_state = evaluator.problem_state
    else:
        problem, p_state = evaluator
    fitness, p_state, _ = problem.eval(key, pop, p_state)
    return fitness


def _evosax_mjx_eval(evaluator, pop, state, key):
    """Executes MalthusJAX evaluation on raw Evosax populations."""

    # 1. Inspect the evaluator's genome configuration to determine the genome type
    # For now, Evosax integration strictly assumes RealGenome continuous optimization
    from malthusjax.core.genome.real_genome import RealGenome, RealPopulation

    # Access the config from the evaluator. Depending on the evaluator type,
    # the config attribute structure might vary, but standard evaluators have config.genome_config
    if hasattr(evaluator.config, "genome_config"):
        config = evaluator.config.genome_config
    else:
        # Fallback if the evaluator uses a different config pattern
        from malthusjax.core.genome.real_genome import RealGenomeConfig

        config = RealGenomeConfig(shape=pop.shape[1:], dtype=pop.dtype)

    # 2. Reconstruct the MalthusJAX population structure from the raw `pop` tensor
    genomes = RealGenome.from_tensor(pop, config)
    population = RealPopulation(
        genes=genomes, fitness=jnp.full(pop.shape[0], -jnp.inf), config=config
    )

    # 3. Evaluate using the standard MalthusJAX batched evaluator
    population = evaluator.evaluate_population(population)

    return population.fitness


@adapter(
    framework="evosax",
    state_mapping={"init": "_adapter_init", "step": "_adapter_step"},
    eval_translators={EvalMode.NATIVE: _evosax_native_eval, EvalMode.MALTHUSJAX: _evosax_mjx_eval},
    metrics_mapping={
        "best_fitness": "best_fitness",
        "mean_fitness": "mean_fitness",
        "std_fitness": "std_fitness",
    },
)
class EvosaxEngineAdapter:
    """Universal Evosax Adapter automatically generated by the @adapter decorator."""

    def _adapter_init(
        self, strategy: Any, key: chex.Array, params: Any, pop_init: Any = None
    ) -> Any:
        # In MalthusJAX's universal adapter core, the init phase takes the key and initializes the state.
        # However, evosax's strategy.init requires pop_init and fit_init if they are not generated.
        # Since we decoupled this, we just call strategy.init with dummy/initial values.

        # We need to construct pop_init and fit_init properly if not provided.
        # But for brevity, we assume the user provides them or the strategy handles it.
        # If we need the problem to sample the init population:
        eval_mode = getattr(self, "eval_mode", "native")
        if eval_mode == "native":
            problem, p_state = getattr(self, "_framework_evaluator", (None, None))
            if pop_init is None and problem is not None:
                keys = jax.random.split(key, getattr(self, "pop_size", 100))
                pop_init = jax.vmap(problem.sample)(keys)

            fit_init = jnp.zeros(getattr(self, "pop_size", 100))
            if problem is not None:
                fit_init, p_state, _ = problem.eval(key, pop_init, p_state)
                if getattr(self, "maximize", False):
                    fit_init = -fit_init
                self._framework_evaluator = (problem, p_state)  # Update state
        else:
            # For MalthusJAX mode, evaluator is stored directly
            evaluator = getattr(self, "_framework_evaluator", None)

            if pop_init is None:
                # If no pop_init, evosax typically uses the init_solution provided to the strategy
                pop_size = getattr(self, "pop_size", 100)
                num_dims = getattr(self, "num_dims", 1)
                bounds = getattr(self, "bounds", (-5.0, 5.0))
                keys = jax.random.split(key, pop_size)
                pop_init = jax.random.uniform(
                    key, (pop_size, num_dims), minval=bounds[0], maxval=bounds[1]
                )

            fit_init = _evosax_mjx_eval(evaluator, pop_init, None, key)

        if type(strategy).__name__ in distribution_based_algorithms:
            # Distribution-based algorithms expect a mean instead of a population
            mean_init = jnp.mean(pop_init, axis=0)
            state = strategy.init(key, mean_init, params)
        else:
            state = strategy.init(key, pop_init, fit_init, params)
        return state

    def _adapter_step(
        self,
        strategy: Any,
        state: Any,
        key: chex.Array,
        params: Any,
        evaluator: Any,
        eval_translator: Callable,
    ) -> Tuple[Any, Dict]:
        key_ask, key_eval, key_tell = jax.random.split(key, 3)

        # 1. Ask
        population, state = strategy.ask(key_ask, state, params)

        # 2. Evaluate (Delegated to translator)
        fitness = eval_translator(evaluator, population, state, key_eval)

        # 3. Process metrics for objective direction
        maximize = getattr(self, "maximize", False)
        mean_fit = jnp.mean(fitness)
        std_fit = jnp.std(fitness)
        best_fit_obj = jnp.max(fitness) if maximize else jnp.min(fitness)

        tell_fitness = -fitness if maximize else fitness

        # 4. Tell
        state, metrics = strategy.tell(key_tell, population, tell_fitness, state, params)

        # Pack metrics
        metrics = dict(metrics)
        metrics["best_fitness_in_generation"] = best_fit_obj
        metrics["mean_fitness"] = mean_fit
        metrics["std_fitness"] = std_fit

        return state, metrics


import jax.random as jr

from malthusjax.core.fitness.base import BaseEvaluator
from malthusjax.core.fitness.bbob_evaluator import BBOBConfig, BBOBEvaluator
from malthusjax.core.genome.real_genome import RealGenomeConfig


def build_evosax_engine(
    strategy_name: str = "SimpleGA",
    *,
    evaluator: Optional[BaseEvaluator[Any, Any, Any]] = None,
    fitness_spec: Optional[str] = None,
    pop_size: int = 50,
    generations: int = 100,
    bounds: Tuple[float, float] = (-5.0, 5.0),
    maximize: bool = False,
    seed: int = 42,
    strategy_params: Optional[Dict[str, Any]] = None,
    initial_population: Any = None,
    prng_impl: Optional[str] = None,
    history_metrics: Optional[Sequence[str]] = None,
    use_python_loop: bool = False,
    **kwargs: Any,
) -> EvosaxEngineAdapter:
    """Build an :class:`EvosaxEngineAdapter` from high-level specs."""
    if "num_generations" in kwargs:
        generations = int(kwargs.pop("num_generations"))

    if evaluator is None:
        raise ValueError("build_evosax_engine requires an evaluator argument")

    if fitness_spec is not None and isinstance(evaluator, BBOBEvaluator):
        from .catalog import OperatorCatalog

        cat = OperatorCatalog()
        parsed_name, parsed_params = cat.parse_spec(fitness_spec)
        fn = parsed_params.get("fn_name", parsed_name)
        dims = parsed_params.get("dim", parsed_params.get("num_dims"))
        if dims is None:
            dims = evaluator.config.num_dims
        if "seed" in parsed_params:
            seed = parsed_params["seed"]
        if "maximize" in parsed_params:
            maximize = parsed_params["maximize"]
        evaluator = BBOBEvaluator.create(
            BBOBConfig(fn_name=fn, num_dims=dims, seed=seed, maximize=maximize)
        )

    if strategy_name not in EVOSAX_STRATEGIES:
        raise KeyError(f"Unknown evosax strategy '{strategy_name}'. Available: {list_strategies()}")

    rng = jr.PRNGKey(seed)

    if isinstance(evaluator, BBOBEvaluator):
        problem = evaluator.evosax_problem
        problem_state = evaluator.problem_state
        num_dims = evaluator.config.num_dims
        eval_mode = EvalMode.NATIVE
    else:
        problem = None
        problem_state = None
        # Infer dimensions from the MalthusJAX evaluator's genome config
        if hasattr(evaluator, "config"):
            if hasattr(evaluator.config, "genome_config") and hasattr(
                evaluator.config.genome_config, "shape"
            ):
                num_dims = evaluator.config.genome_config.shape[0]
            elif hasattr(evaluator.config, "dim"):
                num_dims = getattr(evaluator.config, "dim")
                RealGenomeConfig(shape=(num_dims,))
            elif hasattr(evaluator.config, "num_dims"):
                num_dims = getattr(evaluator.config, "num_dims")
            elif "num_dims" in kwargs or "genome_length" in kwargs:
                num_dims = kwargs.get("num_dims", kwargs.get("genome_length"))
            else:
                raise ValueError(
                    f"Evaluator {evaluator} does not provide a valid genome_config shape."
                )
        elif "num_dims" in kwargs or "genome_length" in kwargs:
            num_dims = kwargs.get("num_dims", kwargs.get("genome_length"))
        else:
            raise ValueError(f"Evaluator {evaluator} does not provide a valid genome_config shape.")
        eval_mode = EvalMode.MALTHUSJAX

    init_solution = jr.uniform(rng, (num_dims,), minval=bounds[0], maxval=bounds[1])

    strategy_cls = EVOSAX_STRATEGIES[strategy_name]
    if strategy_name == "RandomSearch":

        def sampling_fn(k):
            return jr.uniform(k, (num_dims,), minval=bounds[0], maxval=bounds[1])

        strategy = strategy_cls(
            population_size=pop_size, solution=init_solution, sampling_fn=sampling_fn
        )
    else:
        strategy = strategy_cls(population_size=pop_size, solution=init_solution)

    params = strategy.default_params
    if strategy_params:
        params_kwargs = {}
        strategy_kwargs = {}
        params_fields = set(params.__dict__.keys()) if hasattr(params, "__dict__") else set()

        for key, value in strategy_params.items():
            if key == "mutation_std" and isinstance(value, (int, float)):
                import optax

                strategy_kwargs["std_schedule"] = optax.constant_schedule(value)
            elif key in params_fields:
                params_kwargs[key] = value
            elif hasattr(strategy, key):
                strategy_kwargs[key] = value
            else:
                raise KeyError(f"Unknown evosax strategy parameter '{key}'. ")

        if params_kwargs:
            params = params.replace(**params_kwargs)
        for key, value in strategy_kwargs.items():
            setattr(strategy, key, value)

    return EvosaxEngineAdapter(
        strategy=strategy,
        params=params,
        problem=problem,
        problem_state=problem_state,
        pop_size=pop_size,
        num_generations=generations,
        num_dims=num_dims,
        bounds=bounds,
        maximize=maximize,
        initial_population=initial_population,
        eval_mode=eval_mode,
        prng_impl=prng_impl,
        evaluator=evaluator,
        history_metrics=history_metrics,
        use_python_loop=use_python_loop,
    )
