from typing import Any, Callable, Dict, Optional, Tuple

import chex
import jax.numpy as jnp

from malthusjax.composer.adapters import EvalMode, adapter


def _kozax_native_eval(evaluator, pop, gp_strategy, key):
    """Executes the Kozax native evaluation function."""
    # In Native mode, evaluator is typically a tuple of (data_tuple, evaluate_fn_if_needed)
    # But usually Kozax evaluates via `gp.evaluate_population` which takes data.
    # Let's assume evaluator is the `data` tuple passed to evaluate_population.
    problem, problem_state = evaluator
    return gp_strategy.evaluate_population(pop, problem, key)


def _kozax_mjx_eval(evaluator, pop, gp_strategy, key):
    """Executes MalthusJAX evaluation on raw Kozax populations."""
    raise NotImplementedError("EvalMode.MALTHUSJAX is not implemented yet for Kozax.")


@adapter(
    framework="kozax",
    state_mapping={"init": "_adapter_init", "step": "_adapter_step"},
    eval_translators={EvalMode.NATIVE: _kozax_native_eval, EvalMode.MALTHUSJAX: _kozax_mjx_eval},
    metrics_mapping={
        "best_fitness": "best_fitness_in_generation",
        "mean_fitness": "mean_fitness",
        "std_fitness": "std_fitness",
    },
)
class KozaxEngineAdapter:
    """Universal Kozax Adapter automatically generated by the @adapter decorator."""

    def _adapter_init(
        self, strategy: Any, key: chex.Array, params: Any, pop_init: Any = None
    ) -> Any:
        # If pop_init is provided, use it. Otherwise, sample from Kozax's native initialize_population
        if pop_init is not None:
            return pop_init

        # Initialize natively
        return strategy.initialize_population(key)

    def _adapter_step(
        self,
        strategy: Any,
        state: Any,
        key: chex.Array,
        params: Any,
        evaluator: Any,
        eval_translator: Callable[..., Any],
    ) -> Tuple[Any, Dict[str, Any]]:
        pop = state

        # Evaluate
        # eval_translator returns (fitness, updated_pop)
        fitness, updated_pop = eval_translator(evaluator, pop, strategy, key)

        # In Kozax, it's always minimization. If we want to report maximization metrics:
        maximize = getattr(self, "maximize", False)

        reported_fitness = -fitness if maximize else fitness

        metrics = {
            "best_fitness_in_generation": jnp.min(reported_fitness)
            if not maximize
            else jnp.max(reported_fitness),
            "mean_fitness": jnp.mean(reported_fitness),
            "std_fitness": jnp.std(reported_fitness),
        }

        # Step
        # Kozax's evolve_population handles reproduction/mutation
        new_pop = strategy.evolve_population(updated_pop, fitness, key)

        return new_pop, metrics


def build_kozax_engine(
    strategy_obj: Any,
    evaluator: Any,
    generations: int,
    pop_size: Optional[int] = None,
    maximize: bool = False,
    initial_population: chex.Array = None,
    eval_mode: EvalMode = EvalMode.NATIVE,
    history_metrics: Optional[list[str]] = None,
    use_python_loop: bool = True,
) -> Any:
    """Factory to build a UniversalAdapterEngine for Kozax."""
    if eval_mode == EvalMode.MALTHUSJAX:
        raise ValueError(
            "EvalMode.MALTHUSJAX is not supported for structure-evolving backends like Kozax. "
            "You must use EvalMode.NATIVE and provide an evaluator built specifically for Kozax."
        )

    # pop_size can be extracted from strategy_obj
    if pop_size is None:
        pop_size = strategy_obj.population_size * strategy_obj.num_populations

    return KozaxEngineAdapter(
        strategy=strategy_obj,
        params=None,
        pop_size=pop_size,
        num_generations=generations,
        maximize=maximize,
        initial_population=initial_population,
        eval_mode=eval_mode,
        problem=evaluator if eval_mode == EvalMode.NATIVE else None,
        evaluator=evaluator if eval_mode != EvalMode.NATIVE else None,
        history_metrics=history_metrics,
        use_python_loop=use_python_loop,
    )  # type: ignore[call-arg]
