"""QDax adapter for the BenchmarkRunner.Engine protocol.

Wraps qdax.MAPElites using the universal @adapter decorator.
"""

from __future__ import annotations

from typing import Any, Callable, Dict, Optional

import chex
import jax
import jax.numpy as jnp

from malthusjax.composer.adapters import EvalMode, adapter


def _qdax_native_eval(evaluator, pop, state, key):
    """Executes the QDAX native scoring function."""
    # QDAX scoring functions typically return (fitnesses, descriptors, extra_info, next_key)
    # The universal adapter handles fitness returning, but QDAX's update loop expects the raw evaluator
    # to be inside MAPElites. This function is mostly a placeholder if we need external evaluation, 
    # but for QDAX, evaluation is monolithic inside MAPElites.update.
    pass


@adapter(
    framework="qdax",
    state_mapping={
        "init": "_adapter_init",
        "step": "_adapter_step"
    },
    eval_translators={
        EvalMode.NATIVE: _qdax_native_eval,
        # Will be implemented when we bridge MalthusJAX evaluate_qd
        EvalMode.MALTHUSJAX: None 
    },
    metrics_mapping={
        # QDAX metrics typically includes max_fitness
        "best_fitness": "max_fitness"
    }
)
class QDaxEngineAdapter:
    """Universal QDAX Adapter automatically generated by the @adapter decorator."""
    
    def _adapter_init(self, strategy: Any, key: chex.Array, params: Any, pop_init: Any = None) -> Any:
        # For QDAX, strategy is the MAPElites instance.
        # params would contain centroids, initial variables.
        init_variables = params.get("init_variables")
        centroids = params.get("centroids")
        
        repertoire, emitter_state, randkey = strategy.init(init_variables, centroids, key)
        return (repertoire, emitter_state, randkey)

    def _adapter_step(self, strategy: Any, state: Any, key: chex.Array, params: Any, evaluator: Any, eval_translator: Callable) -> Tuple[Any, Dict]:
        repertoire, emitter_state, randkey = state
        
        repertoire, emitter_state, metrics, randkey = strategy.update(
            repertoire, emitter_state, randkey
        )
        
        # We also manually pack the metrics required
        # Note: the decorator will extract `max_fitness` as `best_fitness`
        
        return (repertoire, emitter_state, randkey), metrics
