from typing import Any, Callable, Dict, Optional, Sequence, Tuple

import chex
import jax
import jax.numpy as jnp

from malthusjax.composer.adapters import EvalMode, adapter
from malthusjax.composer.adapters.metrics import MetricSpec


def list_algorithms() -> list[str]:
    try:
        import inspect

        import tensorneat.algorithm

        algos = []
        for name, obj in inspect.getmembers(tensorneat.algorithm, inspect.isclass):
            if hasattr(obj, "ask") and hasattr(obj, "tell") and name != "BaseAlgorithm":
                algos.append(name)
        return sorted(algos)
    except ImportError:
        return []


def list_genomes() -> list[str]:
    try:
        import inspect

        import tensorneat.genome

        genomes = []
        for name, obj in inspect.getmembers(tensorneat.genome, inspect.isclass):
            if hasattr(obj, "initialize") and name != "BaseGenome":
                genomes.append(name)
        return sorted(genomes)
    except ImportError:
        return []


def list_problems() -> list[str]:
    try:
        import inspect

        import tensorneat.problem

        problems = []
        for name, obj in inspect.getmembers(tensorneat.problem, inspect.isclass):
            if hasattr(obj, "evaluate") and "Base" not in name:
                problems.append(name)
        return sorted(problems)
    except ImportError:
        return []


def _tensorneat_native_eval(evaluator, state, transformed_pop, algorithm, key):
    """Executes the TensorNEAT native evaluation function.

    In native mode, evaluator is assumed to be a TensorNEAT Problem instance.
    We use jax.vmap to run the problem.evaluate function across the population.
    """
    problem, problem_state = evaluator
    pop_size = jax.tree_util.tree_leaves(transformed_pop)[0].shape[0]
    keys = jax.random.split(key, pop_size)

    # Depending on the problem, it might take (state, key, forward, params)
    # The signature in TensorNEAT pipeline is usually:
    # vmap(problem.evaluate, in_axes=(None, 0, None, 0))(state, keys, algorithm.forward, transformed_pop)
    res = jax.vmap(problem.evaluate, in_axes=(None, 0, None, 0))(
        state, keys, algorithm.forward, transformed_pop
    )
    if isinstance(res, tuple):
        fitness = res[0]
    else:
        fitness = res

    # TensorNEAT replaces NaN with -inf
    fitness = jnp.where(jnp.isnan(fitness), -jnp.inf, fitness)
    return fitness


def _tensorneat_mjx_eval(evaluator, state, transformed_pop, algorithm, key):
    """Executes MalthusJAX evaluation on raw TensorNEAT populations."""
    raise NotImplementedError("EvalMode.MALTHUSJAX is not implemented yet for TensorNEAT.")


TENSORNEAT_METRICS = [
    MetricSpec(name="best_fitness", source="best_fitness_in_generation", is_objective_value=True),
    MetricSpec(name="mean_fitness", source="mean_fitness", is_objective_value=True),
    MetricSpec(name="std_fitness", source="std_fitness", is_objective_value=False),
]


@adapter(
    framework="tensorneat",
    state_mapping={"init": "_adapter_init", "step": "_adapter_step"},
    eval_translators={
        EvalMode.NATIVE: _tensorneat_native_eval,
        EvalMode.MALTHUSJAX: _tensorneat_mjx_eval,
    },
    metrics_catalog=TENSORNEAT_METRICS,
    backend_maximizes=True,
)
class TensorNEATEngineAdapter:
    """Universal TensorNEAT Adapter automatically generated by the @adapter decorator."""

    maximize: bool

    def _adapter_init(
        self, algorithm: Any, key: chex.Array, params: Any, pop_init: Any = None
    ) -> Any:
        # TensorNEAT requires a State object which we construct and inject the randkey into
        # Since TensorNEAT is an external dependency, we try to import its State class
        try:
            from tensorneat.common import State
        except ImportError:
            raise ImportError(
                "TensorNEAT is not installed. Please install it to use the TensorNEAT adapter."
            )

        state = State()
        state = state.register(randkey=key)
        state = algorithm.setup(state)

        # If pop_init is provided, overwrite the randomly generated population
        if pop_init is not None:
            # pop_init from tensorneat engine/emitter should be a tuple (nodes, conns)
            # or from TensorNeatPopulation object
            if hasattr(pop_init, "genes") and hasattr(pop_init.genes, "values"):
                nodes, conns = pop_init.genes.values
            elif hasattr(pop_init, "values"):
                nodes, conns = pop_init.values
            elif isinstance(pop_init, tuple) and len(pop_init) == 2:
                nodes, conns = pop_init
            else:
                raise ValueError(
                    f"TensorNEAT initial_population must be a tuple (nodes, conns) or TensorNeatGenome, got {type(pop_init)}"
                )

            state = state.update(pop_nodes=nodes, pop_conns=conns)

        return state

    def _adapter_step(
        self,
        algorithm: Any,
        state: Any,
        key: chex.Array,
        params: Any,
        evaluator: Any,
        eval_translator: Callable[..., Any],
    ) -> Tuple[Any, Dict[str, Any]]:
        # Update randkey
        state = state.update(randkey=key)

        # 1. Ask
        pop = algorithm.ask(state)

        # 2. Transform
        transformed_pop = jax.vmap(algorithm.transform, in_axes=(None, 0))(state, pop)

        # 3. Evaluate
        fitness = eval_translator(evaluator, state, transformed_pop, algorithm, key)

        # TensorNEAT maximizes natively.
        valid_mask = jnp.isfinite(fitness)

        # If user wants to minimize, we negate the fitness so TensorNEAT maximizes the negative.
        tn_fitness = jnp.where(self.maximize, fitness, -fitness)
        safe_tn_fitness = jnp.where(valid_mask, tn_fitness, -jnp.inf)

        metrics = {
            "best_fitness_in_generation": jnp.where(
                self.maximize,
                jnp.max(jnp.where(valid_mask, fitness, -jnp.inf)),
                jnp.min(jnp.where(valid_mask, fitness, jnp.inf)),
            ),
            "mean_fitness": jnp.mean(jnp.where(valid_mask, fitness, jnp.nan)),
            "std_fitness": jnp.std(jnp.where(valid_mask, fitness, jnp.nan)),
        }

        # 4. Tell
        state = algorithm.tell(state, safe_tn_fitness)

        return state, metrics


def build_tensorneat_engine(
    algorithm: Any,
    evaluator: Any,
    generations: int,
    pop_size: Optional[int] = None,
    maximize: bool = True,
    eval_mode: EvalMode = EvalMode.NATIVE,
    history_metrics: Optional[Sequence[str]] = None,
    use_python_loop: bool = False,
    initial_population: Optional[Any] = None,
) -> Any:
    """Factory to build a UniversalAdapterEngine for TensorNEAT."""
    if eval_mode == EvalMode.MALTHUSJAX:
        raise ValueError(
            "EvalMode.MALTHUSJAX is not supported for structure-evolving backends like TensorNEAT. "
            "You must use EvalMode.NATIVE and provide an evaluator built specifically for TensorNEAT."
        )

    # TensorNEAT specifies pop_size at instantiation of the algorithm (e.g. NEAT(pop_size=...))
    if pop_size is None and hasattr(algorithm, "pop_size"):
        pop_size = algorithm.pop_size
    elif pop_size is None:
        pop_size = 100  # Safe fallback

    problem_state = None
    if eval_mode == EvalMode.NATIVE:
        if isinstance(evaluator, tuple):
            problem, problem_state = evaluator
        else:
            problem = evaluator
        mjx_evaluator = None
    else:
        problem = None
        mjx_evaluator = evaluator

    return TensorNEATEngineAdapter(
        strategy=algorithm,
        params=None,
        problem=problem,
        problem_state=problem_state,
        pop_size=pop_size,
        num_generations=generations,
        maximize=maximize,
        eval_mode=eval_mode,
        evaluator=mjx_evaluator,
        history_metrics=history_metrics,
        use_python_loop=use_python_loop,
        state_has_randkey=True,  # Signal to base adapter that state contains the key
        initial_population=initial_population,
        backend_maximizes=True,
    )  # type: ignore[call-arg]
