from typing import Any, Callable, Dict, Tuple

import chex
import jax
import jax.numpy as jnp

from malthusjax.composer.adapters import EvalMode, adapter


def list_algorithms() -> list[str]:
    try:
        import inspect

        import tensorneat.algorithm

        algos = []
        for name, obj in inspect.getmembers(tensorneat.algorithm, inspect.isclass):
            if hasattr(obj, "ask") and hasattr(obj, "tell") and name != "BaseAlgorithm":
                algos.append(name)
        return sorted(algos)
    except ImportError:
        return []


def list_genomes() -> list[str]:
    try:
        import inspect

        import tensorneat.genome

        genomes = []
        for name, obj in inspect.getmembers(tensorneat.genome, inspect.isclass):
            if hasattr(obj, "initialize") and name != "BaseGenome":
                genomes.append(name)
        return sorted(genomes)
    except ImportError:
        return []


def list_problems() -> list[str]:
    try:
        import inspect

        import tensorneat.problem

        problems = []
        for name, obj in inspect.getmembers(tensorneat.problem, inspect.isclass):
            if hasattr(obj, "evaluate") and "Base" not in name:
                problems.append(name)
        return sorted(problems)
    except ImportError:
        return []


def _tensorneat_native_eval(evaluator, state, transformed_pop, algorithm, key):
    """Executes the TensorNEAT native evaluation function.

    In native mode, evaluator is assumed to be a TensorNEAT Problem instance.
    We use jax.vmap to run the problem.evaluate function across the population.
    """
    problem, problem_state = evaluator
    pop_size = jax.tree_util.tree_leaves(transformed_pop)[0].shape[0]
    keys = jax.random.split(key, pop_size)

    # Depending on the problem, it might take (state, key, forward, params)
    # The signature in TensorNEAT pipeline is usually:
    # vmap(problem.evaluate, in_axes=(None, 0, None, 0))(state, keys, algorithm.forward, transformed_pop)
    fitness = jax.vmap(problem.evaluate, in_axes=(None, 0, None, 0))(
        state, keys, algorithm.forward, transformed_pop
    )

    # TensorNEAT replaces NaN with -inf
    fitness = jnp.where(jnp.isnan(fitness), -jnp.inf, fitness)
    return fitness


def _tensorneat_mjx_eval(evaluator, state, transformed_pop, algorithm, key):
    """Executes MalthusJAX evaluation on raw TensorNEAT populations."""
    raise NotImplementedError("EvalMode.MALTHUSJAX is not implemented yet for TensorNEAT.")


@adapter(
    framework="tensorneat",
    state_mapping={"init": "_adapter_init", "step": "_adapter_step"},
    eval_translators={
        EvalMode.NATIVE: _tensorneat_native_eval,
        EvalMode.MALTHUSJAX: _tensorneat_mjx_eval,
    },
    metrics_mapping={
        "best_fitness": "best_fitness_in_generation",
        "mean_fitness": "mean_fitness",
        "std_fitness": "std_fitness",
    },
)
class TensorNEATEngineAdapter:
    """Universal TensorNEAT Adapter automatically generated by the @adapter decorator."""

    def _adapter_init(
        self, algorithm: Any, key: chex.Array, params: Any, pop_init: Any = None
    ) -> Any:
        # TensorNEAT requires a State object which we construct and inject the randkey into
        # Since TensorNEAT is an external dependency, we try to import its State class
        try:
            from tensorneat.common import State
        except ImportError:
            raise ImportError(
                "TensorNEAT is not installed. Please install it to use the TensorNEAT adapter."
            )

        state = State()
        state = state.register(randkey=key)
        state = algorithm.setup(state)
        return state

    def _adapter_step(
        self,
        algorithm: Any,
        state: Any,
        key: chex.Array,
        params: Any,
        evaluator: Any,
        eval_translator: Callable,
    ) -> Tuple[Any, Dict]:
        # Update randkey
        state = state.update(randkey=key)

        # 1. Ask
        pop = algorithm.ask(state)

        # 2. Transform
        transformed_pop = jax.vmap(algorithm.transform, in_axes=(None, 0))(state, pop)

        # 3. Evaluate
        fitness = eval_translator(evaluator, state, transformed_pop, algorithm, key)

        # TensorNEAT natively maximizes. If the user passed maximize=False to the adapter,
        # it implies they want the reported metrics to reflect a minimization objective,
        # while letting TensorNEAT internally maximize the natively returned (presumably inverted) fitness.
        maximize = getattr(self, "maximize", True)

        reported_fitness = fitness if maximize else -fitness

        # TensorNEAT masks invalid with -inf. If we minimize, we should mask with inf.
        valid_mask = jnp.isfinite(fitness)
        safe_reported = jnp.where(valid_mask, reported_fitness, -jnp.inf if maximize else jnp.inf)

        metrics = {
            "best_fitness_in_generation": jnp.max(safe_reported)
            if maximize
            else jnp.min(safe_reported),
            "mean_fitness": jnp.mean(jnp.where(valid_mask, reported_fitness, jnp.nan)),
            "std_fitness": jnp.std(jnp.where(valid_mask, reported_fitness, jnp.nan)),
        }

        # 4. Tell
        state = algorithm.tell(state, fitness)

        return state, metrics


def build_tensorneat_engine(
    algorithm: Any,
    evaluator: Any,
    generations: int,
    pop_size: int = None,
    maximize: bool = True,
    eval_mode: EvalMode = EvalMode.NATIVE,
    history_metrics: list[str] = None,
    use_python_loop: bool = False,
):
    """Factory to build a UniversalAdapterEngine for TensorNEAT."""
    # TensorNEAT specifies pop_size at instantiation of the algorithm (e.g. NEAT(pop_size=...))
    if pop_size is None and hasattr(algorithm, "pop_size"):
        pop_size = algorithm.pop_size
    elif pop_size is None:
        pop_size = 100  # Safe fallback

    problem_state = None
    if eval_mode == EvalMode.NATIVE:
        if isinstance(evaluator, tuple):
            problem, problem_state = evaluator
        else:
            problem = evaluator
        mjx_evaluator = None
    else:
        problem = None
        mjx_evaluator = evaluator

    return TensorNEATEngineAdapter(
        strategy=algorithm,
        params=None,
        problem=problem,
        problem_state=problem_state,
        pop_size=pop_size,
        num_generations=generations,
        maximize=maximize,
        eval_mode=eval_mode,
        evaluator=mjx_evaluator,
        history_metrics=history_metrics,
        use_python_loop=use_python_loop,
        state_has_randkey=True,  # Signal to base adapter that state contains the key
    )
