"""Input/output helpers for experiment results.

This module handles reading and writing of JSON and CSV artifacts produced by
benchmark runs.  All writing is performed via atomic temp files to avoid
corruption, and a convenience function builds per-seed directories for
additional outputs.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Dict

import chex
import jax.numpy as jnp
import numpy as np

from .results import ExperimentResult


def write_summary_json(experiment_result: ExperimentResult, path: Path | str) -> None:
    """Persist an experiment summary to disk as JSON.

    The target path is created if necessary, and the data is first written to
    a ``.json.tmp`` temporary file which is then atomically renamed.  This
    guards against partial writes if the process is interrupted.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    # Atomic write: write to temp file, then rename
    temp_path = path.with_suffix(".json.tmp")
    try:
        with temp_path.open("w") as f:
            json.dump(experiment_result.to_dict(), f, indent=2)
        temp_path.rename(path)
    except Exception:
        # Clean up temp file on error
        if temp_path.exists():
            temp_path.unlink()
        raise


def read_summary_json(path: Path | str) -> ExperimentResult:
    """Load an :class:`ExperimentResult` from a JSON file written by
    :func:`write_summary_json`.
    """
    path = Path(path)
    with path.open("r") as f:
        data = json.load(f)
    return ExperimentResult.from_dict(data)


def write_histories_csv(experiment_result: ExperimentResult, path: Path | str) -> None:
    """Dump the concatenated run histories to a CSV file with a seed column.

    The headers are inferred from the union of keys present in the histories,
    and an empty file with just a header is produced if there are no rows.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    combined = experiment_result.combined_history()
    if not combined:
        # Write empty CSV with just headers
        with path.open("w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["seed"])
        return

    # Get all unique keys across all rows for header
    all_keys: set[str] = set()
    for row in combined:
        all_keys.update(row.keys())

    # Ensure 'seed' comes first
    headers = ["seed"] + sorted(k for k in all_keys if k != "seed")

    temp_path = path.with_suffix(".csv.tmp")
    try:
        with temp_path.open("w", newline="") as f:
            dict_writer = csv.DictWriter(f, fieldnames=headers)
            dict_writer.writeheader()
            dict_writer.writerows(combined)
        temp_path.rename(path)
    except Exception:
        if temp_path.exists():
            temp_path.unlink()
        raise


def ensure_seed_folder(output_dir: Path | str, seed: int) -> Path:
    """Ensure a per-seed subdirectory exists and return its path.

    The directory is named ``seed_XXXX`` where XXXX is the zero-padded seed
    value.  This is convenient for organising artifacts generated by
    individual runs.
    """
    output_dir = Path(output_dir)
    seed_dir = output_dir / f"seed_{seed:04d}"
    seed_dir.mkdir(parents=True, exist_ok=True)
    return seed_dir


def write_experiment_artifacts(
    experiment_result: ExperimentResult,
    output_dir: Path | str,
    write_csv: bool = True,
    write_json: bool = True,
) -> Dict[str, Path]:
    """Emit all standard artifacts for an experiment and report their paths.

    Depending on the flags the summary JSON and combined histories CSV are
    written.  In all cases per-seed subdirectories are created and their
    locations are returned in the resulting mapping.
    """
    output_dir = Path(output_dir)
    written_paths = {}

    if write_json:
        json_path = output_dir / "summary.json"
        write_summary_json(experiment_result, json_path)
        written_paths["summary_json"] = json_path

    if write_csv:
        csv_path = output_dir / "histories_combined.csv"
        write_histories_csv(experiment_result, csv_path)
        written_paths["histories_csv"] = csv_path

    # Create seed folders for future per-seed artifacts
    for run in experiment_result.runs:
        seed_dir = ensure_seed_folder(output_dir, run.seed)
        written_paths[f"seed_{run.seed:04d}"] = seed_dir

    return written_paths


class DataLoader:
    """Universal data loader for various formats."""

    @staticmethod
    def load_csv(path: Path | str) -> chex.Array:
        """Load CSV file into a JAX array."""
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(f"Missing data file: {path}")
        try:
            data = np.loadtxt(path, delimiter=",")
            return jnp.asarray(data)
        except Exception as e:
            raise ValueError(f"Failed to load CSV {path}: {e}") from e

    @staticmethod
    def load_npz(path: Path | str) -> dict[str, chex.Array]:
        """Load .npz archive into JAX arrays."""
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(f"Missing data file: {path}")
        try:
            with np.load(path) as data:
                return {k: jnp.asarray(v) for k, v in data.items()}
        except Exception as e:
            raise ValueError(f"Failed to load NPZ {path}: {e}") from e

    @staticmethod
    def load_tsplib(path: Path | str) -> chex.Array:
        """Load TSPLib distance matrix.

        Currently supports EDGE_WEIGHT_TYPE=EUC_2D coordinate lists.
        """
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(f"Missing data file: {path}")

        coords = []
        parsing_coords = False
        with open(path, "r") as f:
            for line in f:
                line = line.strip()
                if line == "NODE_COORD_SECTION":
                    parsing_coords = True
                    continue
                if line == "EOF":
                    break
                if parsing_coords:
                    parts = line.split()
                    if len(parts) >= 3:
                        coords.append([float(parts[1]), float(parts[2])])

        if not coords:
            raise ValueError(f"Could not parse valid coordinates from TSPLib file: {path}")

        coords_arr = np.array(coords)
        diff = coords_arr[:, np.newaxis, :] - coords_arr[np.newaxis, :, :]
        dist_matrix = np.sqrt(np.sum(diff**2, axis=-1))

        return jnp.asarray(dist_matrix)

    @classmethod
    def load_any(cls, path: Path | str) -> chex.Array | dict[str, chex.Array]:
        """Auto-detect format and load."""
        path_str = str(path).lower()
        if path_str.endswith(".csv"):
            return cls.load_csv(path)
        elif path_str.endswith(".npz"):
            return cls.load_npz(path)
        elif path_str.endswith(".tsp") or path_str.endswith(".txt"):
            return cls.load_tsplib(path)
        else:
            raise ValueError(f"Unsupported file extension: {path}")
