"""Statistical comparison layer for parity and benchmark analysis.

DEPRECATED: This module has been refactored into the `malthusjax.stats` package.
Please update your imports.
"""

import warnings

warnings.warn(
    "Importing from malthusjax.benchmarking.statistics is deprecated. "
    "Please import from malthusjax.stats instead.",
    DeprecationWarning,
    stacklevel=2,
)

from malthusjax.stats import (
    DiagnosticResult,
    EffectSizeResult,
    ExpectedDirection,
    HypothesisKind,
    MetricVector,
    MultipleTestingPolicy,
    OLSResult,
    PairedMetricDataset,
    PairedSample,
    RegressionDataset,
    Sidedness,
    StatisticalComparator,
    StatisticalComparisonResult,
    StatisticalComparisonSpec,
    StatisticalSpecError,
    StatisticalSuiteResult,
    TestResult,
    TOSTResult,
    adjust_pvalues,
    apply_decision_rule,
    attach_adjusted_pvalues,
    cohens_dz,
    compare_paired_arrays,
    compute_effect_sizes,
    compute_standard_tests,
    compute_tost_paired,
    fdr_bh,
    glass_delta,
    holm_bonferroni,
    infer_scipy_alternative,
    paired_dataset_from_artifacts,
    paired_dataset_from_comparison,
    paired_dataset_from_experiments,
    paired_t,
    rank_biserial,
    sign_test,
    tost,
    validate_spec,
    wilcoxon,
)

__all__ = [
    "MetricVector",
    "PairedSample",
    "RegressionDataset",
    "StatisticalSpecError",
    "HypothesisKind",
    "Sidedness",
    "ExpectedDirection",
    "MultipleTestingPolicy",
    "StatisticalComparisonSpec",
    "PairedMetricDataset",
    "TestResult",
    "TOSTResult",
    "EffectSizeResult",
    "DiagnosticResult",
    "OLSResult",
    "StatisticalComparisonResult",
    "StatisticalSuiteResult",
    "validate_spec",
    "infer_scipy_alternative",
    "wilcoxon",
    "paired_t",
    "sign_test",
    "tost",
    "compute_standard_tests",
    "compute_tost_paired",
    "cohens_dz",
    "rank_biserial",
    "glass_delta",
    "compute_effect_sizes",
    "holm_bonferroni",
    "fdr_bh",
    "adjust_pvalues",
    "apply_decision_rule",
    "compare_paired_arrays",
    "StatisticalComparator",
    "attach_adjusted_pvalues",
    "paired_dataset_from_experiments",
    "paired_dataset_from_comparison",
    "paired_dataset_from_artifacts",
]
